### PR TITLE
WIP: Time Series

### PR DESCRIPTION
**Pull request by Lane**
supercedes #378 and #399, all time series work and reviews to be completed in this PR and then merged when complete.

## TODO

- [x] style entire "sentence" of metric/population/facility selection elements
- [x] styling updates to match mockups
- [x] chart legend 
  - [x] stack labels instead of overlap
  - [x] truncate facility name if it exceeds the length of the space available (eg. Los Angeles Fiel... instead of Los Angeles Field Office)

## Resources

- [figma mockups](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=1611%3A0)

CBB - Time Series 2
CBB - Time Series 3
Time series mobile 4
Time series mobile 1 c

### CODE REVIEW

**Comment by Lane** [comment]
@touchRED  looking good so far, seeing a few issue that need to be fixed up:

- [ ] getting an error on some facilities (e.g. "All ICE Facilities" or  "Non Institution Locations, Oregon").  also happens when switching to some metrics (e.g. Tests), or switching to "Staff"
image

- [ ] need more space for facility names.  switch to state abbreviations instead of full name.  increase right margin on devices where space allows.  (lengthwise, ideally would like to be able to fit full "California Institution For Men" here.). 

image

- [ ] should display empty chart (show axis but no lines) with a hint to add a location when no locations are shown

image

- [ ] axis line and text color should match [figma mockups](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=1611%3A0)

- [ ] line label colors do not match lines, or are maybe labelling the wrong lines?

image

**Comment by touchRED** [comment]
@Lane thanks! requested fixes are good to go ✅

**Comment by Lane** [comment]
@touchRED thanks! few more touchups:

- [ ] still seeing label overlap in places (see image)
- [ ] y axis labels should match selected metric (pull language from `en.json` using `getLang` utility function

image

**Comment by touchRED** [comment]
@Lane looks like we might also need to reduce the font size on the controls sentence? if we don't want "among incarcerated people" to break to two lines, that is

**Comment by Lane** [comment]
yeah good call.  lets leave it for now and we can let Sasha assess if we need to drop heading sizes once the rest of the feature is wrapped up.

**Comment by Lane** [comment]
a couple more additions based on client review:

- [ ] add conditional caption text under chart when data for certain locations is not available.  (e.g. "`{metric}` for `{group}` is unavailable for `{facilities}`"
- [ ] add data notes button + modal (similar to tables) under chart or under caption if there is one.
- [ ] allow data notes to be added via CMS

**Comment by Lane** [comment]
@touchRED [deployed a preview](https://deploy-preview-450--covid-19-behind-bars.netlify.app/) of the latest and noticing some disappearing lines when changing locations.  to reproduce:

1. open the home page
2. got to the time series and add a few locations
  - locations display as expected
3. edit the locations and remove one
  - several locations disappear, labels no longer correspond to lines


https://user-images.githubusercontent.com/21034/126688153-739d1943-c0d6-4404-81b8-9bec3594c440.mov

**Comment by touchRED** [comment]
@Lane all of the above should be addressed ✅

**Comment by Lane** [comment]
@touchRED amazing! soooo close to wrapping, one more request:

- [ ] default locations should be configurable via CMS

thinking the best approach here might be to load the `allFacilities.csv` with a raw file loader:

```
import allFacilities from "raw-loader!../../../static/data/allFacilities.csv";
```

then use something like [d3 csvParse](https://github.com/d3/d3-dsv#dsv_parse) to parse the data, then shape it into the format needed for the [netlify cms select widget](https://www.netlifycms.org/docs/widgets/select/)

once this is in, i think we should be good! 🤞  thanks so much for all your work on this, it looks great.

**Comment by touchRED** [comment]
@Lane good call! this is working great ✅

**Comment by Lane** [comment]
@touchRED adding via CMS works great, thanks! made a couple minor fixes:

- fix data notes for places w/o states so they do not show `undefined`

image

- linting adjustments
- alternate bg colors across sections on the home page

going to merge this into the working branch, thanks again for your work here!  the UCLA team is very excited to see this one go live. 🎉

**Pull request merged**
