### PR TITLE
Time Series Revisions

### PR DESCRIPTION
**Pull request by Lane**
# Tasks

- [x] format number values using the utility functions for ints, rates, etc. (in `/src/components/table/utils.js`)
- [x] remove weekday from the tooltip date
- [x] remove all "Test" metrics from time series (not enough data to be useful)
- [x] change rates to "per 10k" (create a new formatter function that takes the rate value, multiply by 10000 and format as `{value} per 10k`)
- [x] remove "Date" x-axis label
- [x] use a fixed number (5) of y axis ticks across metrics and show an axis line for each label
- [x] update the first x axis tick to include the year (e.g Apr '20)
- [x] increase left margin so the line does not overlap tick labels

image

- [x] instead of showing gaps in lines when data is missing, connect the lines

image

- [x] do not drop rate values to 0 when data is missing

image

- [x] in the auto complete menu of facilities, sort the facilities within the state so the "statewide" option appears as the first option under the state name

image

### CODE REVIEW

**Comment by Lane** [comment]
hey @touchRED i know you're still working on this, just took a quick look before the client checkin.

for this item:

> remove all "Test" metrics from time series (not enough data to be useful)

we only want to remove tests from the time series, not site wide.  so it should still be in the maps and state page table / map.

**Comment by touchRED** [comment]
awesome @Lane thanks for the heads up!

**Comment by touchRED** [comment]
@Lane – I just added:

- time series line smoothing (let me know what you think of this, I made some modifications to the time series data fetching)
- sort statewide before other facility options
- revert sitewide test metric drop
- update metric title for rates (this is sitewide since it seems the app is built to use `getLang` everywhere it can, let me know if you'd like this change to remain exclusively on the time series)

some notes:

- it seems a fixed number of ticks might be more difficult to achieve than intended according to the [visx docs](https://airbnb.io/visx/docs/xychart#Grid_numTicks):

> Approximate number of grid lines. Approximate due to d3 alogrithm, specify tickValues for precise control.

- for the `Web.Group` task, could you give me some specifics on what we're looking to do with this value? only asking since it seems jurisdiction isn't used in the time series

**Comment by hoshmn** [comment]
Hey @touchRED ! Just thought I'd chime in on the task
>     * [ ]  instead of showing gaps in lines when data is missing, connect the lines
that was by design, as I thought it might be misleading to show a continuous line where data is missing. If you revert [this commit](https://github.com/Hyperobjekt/covid-19-behind-bars/commit/72b6f07767c8cce96dfad9f3f598998f15d77563#diff-19c97c4484fe3b29c27476f0920965ab8ebb9d377961728633d7b7db563b3cf0L64) and also take out the ` || facility[newKey]` from the quoted line, I think it would behave as desired -- might also fix
>     * [ ]  do not drop rate values to 0 when data is missing
Hope that's helpful (and if so, sorry I didn't see/chime in earlier)

**Comment by Lane** [comment]
@touchRED thanks for the update!  some notes:

> sort statewide before other facility options

statewide is not showing as the first option for me in the add location autocomplete dropdown.  e.g. Alabama has a "statewide" entry, but it appears down in the list in alphebetical order instead of being placed first in the list:

image

> it seems a fixed number of ticks might be more difficult to achieve than intended according to the visx docs:

ah yeah.  just took a look at the latest and see that the number of tick lines now match up with the tick labels.  before there were sometimes more labels than there were lines, and i think that was their main concern.  i think it's fine as-is for now, but i will review with them to confirm.

> for the Web.Group task, could you give me some specifics on what we're looking to do with this value? only asking since it seems jurisdiction isn't used in the time series

sorry about this, i think i got my wires crossed with the aggregate table issue, you can ignore this.

**Comment by touchRED** [comment]
@Lane whoops! was experimenting with the grid lines and must have pushed some work-in-progress. fixed!

for the "statewide" option sorting – I forgot to mention you'll have to run the prebuild step again

**Comment by touchRED** [comment]
@Lane @hoshmn time series changes reverted per Josh's recommendation ✅

**Comment by touchRED** [comment]
@Lane @hoshmn  time series changes reverted per Josh's recommendation ✅

**Comment by Lane** [comment]
@touchRED thanks for this, looks great!

**Pull request merged**
